# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: people
    weight: 10
  - name: Research
    url: Research
    weight: 20
  - name: Publications
    url: Publications
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: Micellaneous
    url: Micellaneous
    weight: 50
  - name: Contact
    url: contact
    weight: 60
